### ISSUE TITLE
Incorrect error message at register form

### ISSUE THREAD

**Issue by tsvetkovv** [diolive/cache#17]
#### Steps:
1. Go to register page: /Account/Register
2. Type short password (max 6 characters long) in the password field
   3.. Click register
3. You can see incorrect error message.
#### Actual result:

> The Password must be at least 100 and at max 6 characters long
#### Expected result:

> The Password must be at least 6 and at max 100 characters long

**Comment by diolive** [comment]
Thanks, it's format string issue. I'll check it soon.

**Comment by diolive** [comment]
Fixed at 1.5.4.
